#!/bin/bash

#
# ownCloud Android scenario tests
#
# @author Jesus Recio (@jesmrec)
#

help()
{
   echo ""
   echo "Usage: $0 -t <filter>"
   echo ""
   echo -e "\t-t <filter> Used to execute tagged tests. F. ex: @createfolder will send only tests tagged with such label. OR/AND operations are allowed. It is also allowed to use a classpath to execute all the test in such class"
   echo -e ""
   echo -e "Examples:"
   echo -e ""
   echo -e "\t\t ./executeTests -t @createfolder -> This will execute only tests with the tag @createfolder"
   echo -e ""
   echo -e "\t\t ./executeTests -t '@createfolder and @copy' -> This will execute tests tagged with both @createfolder and @copy"
   echo -e ""
   echo -e "\t\t ./executeTests -t '@createfolder or @copy' -> This will execute tests tagged with @createfolder or @copy"
   echo -e ""
   echo -e "\t\t ./executeTests  -> This will execute all the tests"
   echo -e ""
   echo -e "Some environment variables are needed to work as well:"
   echo -e ""
   echo -e "\t\t\$OC_SERVER_URL (mandatory): URL of ownCloud server to test against"
   echo -e ""
   echo -e "\t\t\$UDID_DEVICE (optional): UDID of the device to execute the tests against. Get from adb devices command"
   echo -e ""
   echo -e "\t\t\$APPIUM_URL (optional): Appium server URL. if Appium Server is not specified, will be used \"localhost:4723/wd/hub\""
   echo -e ""
   echo -e "\t\t\$BACKEND (optional): oCIS or oC10. If not specified, will be used oCIS"
   echo -e ""
   echo -e "The option -h: will show this help"
   echo -e ""
   echo -e ""
   exit 1
}

checklogs()
{
  if [ ! -d "logs" ]
  then
    mkdir ./logs
  else
    echo "Logs folder already exists";
  fi
}

checklogs

while getopts "t::h" opt; do
  case $opt in
    t) tags="$OPTARG"
    ;;
    h) help
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done

export oc=$OC_SERVER_URL
export appium=$APPIUM_URL
export udid=$UDID_DEVICE
export backend=$BACKEND

if [ -z "$oc" ]
then
   echo "ownCloud Server URL is missing. Please export the variable OC_SERVER_URL with the server URL to test against";
   help
fi

echo "Appium server: $appium"
echo "oC server: $oc"
echo "tags: $tags"
echo "udid: $udid"
echo "backend: $backend"

if [ -z "$tags" ]
then
 ./gradlew --no-daemon clean test \
  --info \
  -Dappium=$appium \
  -Dudid=$udid \
  -Dserver=$oc \
  -Dbackend=$backend
else
  ./gradlew --no-daemon clean test \
  --info \
  -Dcucumber.filter.tags="$tags" \
  -Dappium=$appium \
  -Ddevice=$udid \
  -Dserver=$oc \
  -Dbackend=$backend
fi
