name: E2E tests

on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * 1-5'  # Monday to Friday at 2:30AM

jobs:
  build_apk:
    uses: owncloud/android/.github/workflows/build-apk.yml@master
    with:
      build_variant: qaRelease
      version: master

  #create_ocis:
  #  uses: ./.github/workflows/ocisbackend.yml
  #  with:
  #    ocis_version: 7.3.0
  #  secrets:
  #    ocis_url: ${{ secrets.OC_SERVER_URL }}
  #    ssh_host_call: ${{ secrets.SSH_HOST }}
  #    ssh_user_call: ${{ secrets.SSH_USER }}
  #    ssh_private_key_call: ${{ secrets.SSH_PRIVATE_KEY }}
  #    ocis_pwd_call: ${{ secrets.OCIS_PWD }}

  tests:
    needs:
      - build_apk
  #    - create_ocis
    uses: ./.github/workflows/e2etests.yml
    with:
      apk: ${{ needs.build_apk.outputs.artifact_name }}
      backend: oCIS
    secrets:
       oc_server_url: ${{ secrets.OC_SERVER_URL }}

  cleanup:
    needs:
      - tests
    uses: ./.github/workflows/cleanup.yml
    secrets:
      ssh_host_call: ${{ secrets.SSH_HOST }}
      ssh_user_call: ${{ secrets.SSH_USER }}
      ssh_private_key_call: ${{ secrets.SSH_PRIVATE_KEY }}
      ocis_pwd_call: ${{ secrets.OCIS_PWD }}
